#!/bin/sh

# disable CTRL-C
trap "" 2

# enable getty "hotkeys"
# - tty2: toggle TDM
# - tty3: turn TDM ON
# - tty4: turn TDM OFF
# - tty5: power off
sed -ibak -e 's|^.*tty2::.*|tty2::askfirst:/usr/bin/tdm_toggle|g;s|^.*tty3::.*|tty3::askfirst:/usr/bin/tdm_on|g;s|^.*tty4::.*|tty4::askfirst:/usr/bin/tdm_off|g;s|.*tty5::.*|tty5::askfirst:/usr/bin/tdm_shutdown|g' /etc/inittab

# mute the "failed in waitforX" pseudo-error
sed -ibak -e 's/^waitforX.*/waitforX \|\| exit/g' /home/tc/.xsession

killall -HUP init

/etc/init.d/services/tdm start
