#!/bin/sh

# disable CTRL-C
trap "" 2

sed -ibak -e 's|^.*tty2::.*|tty2::askfirst:/usr/bin/tdm_toggle|g;s|^.*tty3::.*|tty3::askfirst:/usr/bin/tdm_on|g;s|^.*tty4::.*|tty4::askfirst:/usr/bin/tdm_off|g' /etc/inittab

killall -HUP init

/etc/init.d/services/tdm start
